name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Node (for theme dependencies)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install theme npm dependencies
        run: |
          cd themes/hugo-toigian
          npm install
          cd ../..

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.121.1'
          extended: true

      - name: Build site
        run: hugo --gc --minify

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    needs: build-deploy
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
